### ISSUE TITLE
Single Quotes vs. Double Quotes

### ISSUE THREAD

**Issue by Murilirum** [rs459/bootstrap3-jade-sublime-plugin#11]
Is there a way so that when I autocomplete a `bst-*` function, it has double quotes rather than single quotes? The Jade Linter used for the application I'm working on requires a double quote to go through approval. I'm fine with it personally either way but this would be nice to either add or know to toggle between the two.

**Comment by rs459** [comment]
Hi, i suggest you this plugin > "brackethighligther" , and you can use this command which come from this plugin "swap quotes"
![brackethighligther command swap quotes](https://cloud.githubusercontent.com/assets/876438/10403387/7c46c6b4-6ecb-11e5-8341-d8de5357fa45.png)

**Comment by Murilirum** [comment]
Doesn't solve, nor actually address the issue whatsoever but appreciate the response I guess @rs459 :thumbsup:
