### ISSUE TITLE
This doesn't seem to work on sublime text 3.

### ISSUE THREAD

**Issue by Amit-Kolambikar** [rs459/bootstrap3-jade-sublime-plugin#14]
I tried by setting syntax to jade too. ST version build 3083

**Comment by leighayanid** [comment]
same problem here.. hope this can be fix asap

**Comment by rs459** [comment]
Could you give me more information about your operating system and your list of package ? 

It work's for me on osx and ST 3 build 3083.

**Comment by leighayanid** [comment]
it fails to load all the snippets. everytime I type in bst-, it only shows
 bst-cdn 
 bst-cdn: js
 bst-cdn: css 
 bst-table

I'm using ST 3 build 3083 on Windows 8.1

**Comment by rs459** [comment]
Ok i'll try to download one 'VM' of W8.1 and test it.

Could you give me, the version of the package installed on your system ? 

jade-tmbundle was updated recently, and introduced a bug for my package, it's updated but may be you use an older package, the current version is 1.1.27

`command palette > package control: list packages > bootstrap jade`

![capture d ecran 2015-12-25 a 10 40 22](https://cloud.githubusercontent.com/assets/876438/12001950/f9421d08-aaf3-11e5-94ad-7bd598e077e8.png)

**Comment by leighayanid** [comment]
I installed the latest version but still no luck. same result 
![capture](https://cloud.githubusercontent.com/assets/5248582/12004724/94d000d2-ab26-11e5-8994-74776153f48d.PNG)

**Comment by leighayanid** [comment]
![d](https://cloud.githubusercontent.com/assets/5248582/12004730/29275d20-ab27-11e5-89a5-4b96c71e9222.png)

**Comment by rs459** [comment]
Can you send me you list of package installed ? 

IE: the content of `Packages/User/Package Control.sublime-settings`

Have you installed it through package control or manually with git ?
I see you don't have syntax highlighting do you have setted the language to jade ?
Do you use the lastest version of jade plugin définition ? (v2015.12.01.15.43.39)
 
![capture d ecran 2015-12-26 a 02 04 11](https://cloud.githubusercontent.com/assets/876438/12004765/06a355a8-ab75-11e5-8a1f-7e5d7e75ac4d.png)

**Comment by leighayanid** [comment]
Damn! I forgot to install the jade plugin. It works now. Sorry for that. My bad. Thanks. Happy Holidays :)

**Comment by rs459** [comment]
it's my fault too, i've updated the package with a depedencies.json to tell to sublime 3 to install it at the same time.
