### ISSUE TITLE
I have Sublime Text 3 + Jade installed and it still doesn't work for me

### ISSUE THREAD

**Issue by GeorgiRaichovGeorgiev** [rs459/bootstrap3-jade-sublime-plugin#17]
I use Sublime Text 3.
I installed the "Bootstrap 3 Jade Sublime Plugin".
Also I have "Jade" installed in Sublime Text 3.
But "Bootstrap 3 Jade Sublime Plugin" still doesn't work for me.
I opened file with "jade" extension (.jade) and I chose the "Jade" syntax for this file.
It still doesn't work.
I'll upload a screenshot below.

My "Package Control.sublime-settings" file:

{
    "bootstrapped": false,
    "in_process_packages":
    [
    ],
    "installed_packages":
    [
        "Bootstrap 3 Jade Snippets",
        "Emmet",
        "Jade",
        "Package Control",
        "Sass",
        "SublimeCodeIntel",
        "SublimeLinter",
        "SublimeLinter-csslint",
        "SublimeLinter-jshint",
        "Syntax Highlighting for Sass"
    ]
}

![bootstrap 3 jade snippets problem](https://cloud.githubusercontent.com/assets/10547464/15144223/b9ed08be-16b6-11e6-9947-e50d4bbac024.png)

**Comment by GeorgiRaichovGeorgiev** [comment]
I found what was the problem.

When I write "bst-" after that I have to click Ctrl + Space and all snippets options reveal.
But when I write only "bst-" without clicking Ctrl + Space, I don't have any snippet option revealed.

**Comment by mrmowgli** [comment]
Not working for me either :(

**Comment by rs459** [comment]
@mrmowgli could you provide your OS, and your version of sublime text ?

**Comment by mrmowgli** [comment]
Rebooting works for Jade templates again.  Posting another issue for an update to Pug.

**Comment by rs459** [comment]
Well I close this issue thank's for your feedback
