### ISSUE TITLE
Update for Pug

### ISSUE THREAD

**Issue by mrmowgli** [rs459/bootstrap3-jade-sublime-plugin#18]
Templates don't work when files have a .pug file extension.  Since Pug is the official rebrand of the Jade template language, this should work for both instances.

**Comment by rs459** [comment]
Do you set the syntax to pug ? Do you have pug installed in sublime-text ?

**Comment by mahaknarayan** [comment]
@mrmowgli 
Its works, you just have a tweak a little.

1. Install this via package control in ST. https://github.com/davidrios/jade-tmbundle
2. .pug file being opened, go to view-> syntax-> select jade

Start typing the snippets.

**Comment by mrmowgli** [comment]
@makkBit - Thanks!  I actually just switched to the pug plugin, I suspect it's a fork?  

Closing.
