### ISSUE TITLE
Not working on ST3 3065

### ISSUE THREAD

**Issue by bsienn** [rs459/bootstrap3-jade-sublime-plugin#6]
Hi!
I used Bootstrap 3 plugin from which u forked this. That worked fine when but was using old versions and i found some issues with that. I read your plugin and its being update/maintained. So i try it. But its not working. I use short-tag i.e(bst-alert) or anything and press TAB but nothing happen. In notes it says dependency `Jade language plugin`. i installed `Jade` from package manager, it still not working. Am i missing something. is it something different or am i mistaken. please Guide.

P.S. I removed old Bootstrap plugin.

**Comment by rs459** [comment]
Hi,
`Boostrap 3 plugin` is for html, `Bootstrap 3 jade plugin` is for jade file. 

Do you use it with `*.jade` file ?

**Comment by bsienn** [comment]
Hi rs459, thank you for reply. I am new in front-end development don't know what jade is and how it works. I thought this plugin is better fork of HTML plugin. i tried to search google but did not found any tutorial relevant information about Jade and this plugin. i wanted to use this plugin in my HTML file. From your comment i guess i have too use previous plugin.

**Comment by rs459** [comment]
Jade is a javascript templating language you can find this on : http://jade-lang.com/
It is mostly used with expressjs (http://expressjs.com/) this a web framework for node.js 
Offcourse you can use it alone for generating static html files.

**Comment by bsienn** [comment]
After your comment and explanation, i searched a lot. and now understand. Thank you so much for your efforts on this plugin. and thanks for your reply.
