### ISSUE TITLE
Is it working on sublimetext3?

### ISSUE THREAD

**Issue by leannecrow** [rs459/bootstrap3-jade-sublime-plugin#7]
Doing <b {accordion} doesn't show up the bat-accodrion

**Comment by rs459** [comment]
![sub3bstaccordion](https://cloud.githubusercontent.com/assets/876438/8883748/84e9d9ac-3251-11e5-8cee-a9cde91fbecd.gif)

Yes it work, why do you type 'lower than'  before ? it's jade not html.

**Comment by leannecrow** [comment]
Strange, your work by just entering start with **b** . In my CASE, I have to start it with **<b*** and nothing like what you shows pops up. I have Jade Bootstrap package installed.
![out](https://cloud.githubusercontent.com/assets/8831324/8929675/a6e308ca-3540-11e5-90fc-9cc766eb08be.gif)

**Comment by rs459** [comment]
Ho i see, you have installed ```Bootstrap 3 Snippets``` for jade that's not the same plugin.
you have to install Bootstrap 3 __Jade__ Snippets

![capture d ecran 2015-07-28 a 12 56 39](https://cloud.githubusercontent.com/assets/876438/8929781/20a77c68-3528-11e5-9926-74985054548f.png)

**Comment by leannecrow** [comment]
I have Boostrap 3 Jade Snippets already installed. It also listed when I check in the option "List Packages"

**Comment by leannecrow** [comment]
![out](https://cloud.githubusercontent.com/assets/8831324/8931867/d6d7ad94-3552-11e5-8c45-116f5c48d725.gif)

**Comment by rs459** [comment]
Do you set the language to 'jade', or use it with a file ```*.jade``` ?

**Comment by leannecrow** [comment]
Oh didn't know I was suppose to do it. The syntax wasn't set to Jade which I didn't know I was suppose to do. Thanks!
